# Generated by Django 5.0.6 on 2024-08-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='street_address',
        ),
    ]
