# Generated by Django 5.0.6 on 2024-08-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_address_user_city_town_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_profile_student',
            field=models.BooleanField(default=False),
        ),
    ]
