# Generated by Django 5.0.6 on 2024-08-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_favorites_delete_favorite'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing'),
        ),
    ]
